version: '3.9'

services:
  rl_agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rl_agent_container
    working_dir: /app
    command: python main.py
    volumes:
      - .:/app
    tty: true
